title: Manifesto for Humane Leadership
description: Six Theses and 14 Principles for New Leadership in the Age of Digitalization
repository_url: https://github.com/marcusraitner/manifesto
theme: minima
markdown: kramdown
author: Marcus Raitner
permalink: pretty
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
kramdown:
  input: GFM
  auto_ids: true
